# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import requests
from dotenv import load_dotenv
from pprint import pprint
from openai import OpenAI
import json
import re

input = sys.stdin.readline


load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
openAi_client = OpenAI(api_key=OPENAI_API_KEY)
model = 'gpt-4o-mini'



def get_news(encText="최근 뉴스"):
    url= "https://openapi.naver.com/v1/search/news?query=" + encText
    client_id = os.getenv('NAVER_CLIENT_ID')
    client_secret = os.getenv('NAVER_CLIENT_SECRET')
    params = {
        'language' : 'ko-kr',
    }
    headers = {
        "X-Naver-Client-Id": client_id,
        "X-Naver-Client-Secret": client_secret
    }
    try:
        response = requests.get(url, headers=headers, params=params)
        response.raise_for_status()
        data = response.json()
        items = data.get('items', [])

        # 제목과 링크만 추출하여 새로운 리스트 생성
        refined_news = []
        for item in items:
            # HTML 태그 제거 (예: <b>IT</b> -> IT)
            clean_title = re.sub(r'<[^>]+>', '', item['title'])
            clean_description = re.sub(r'<[^>]+>', '', item['description'])
            refined_news.append({
                'title': clean_title,
                'description': clean_description,
                'link': item['link']
            })

        # 결과 확인을 위한 출력
        pprint(refined_news)
        return refined_news
        # data = response.json()
        # data=data['items']
        # pprint(data)

        # return data
    except Exception as e:
        print(e)

tools = [
    {
        "type": "function",
        "function":{
            "name": "get_news",
            "description": "특정 주제의 뉴스를 가져옵니다.",
            "parameters": {
                "type": "object",
                "properties": {
                    "encText": {
                        "type": "string",
                        "description": "관련 검색어",
                    },
                },
                "required": ["encText"],
            },
        }
    },
]



# 3. 메인 대화 로직
def run_conversation(user_prompt):
    messages = [
        {"role": "system", "content": "너는 뉴스 요약 전문가야. 제공된 뉴스들만 사용하여 답변해줘. 뉴스의 제목은 그대로 출력하고, 내용은 핵심만 요약해서 링크와 함께 보여줘."},
        {"role": "user", "content": user_prompt}
    ]

    response = openAi_client.chat.completions.create(
        model=model,
        messages=messages,
        tools=tools,
        tool_choice="auto"
    )
    
    response_message = response.choices[0].message
    tool_calls = response_message.tool_calls

    if tool_calls:
        messages.append(response_message)
        
        for tool_call in tool_calls:
            function_name = tool_call.function.name
            function_args = json.loads(tool_call.function.arguments)
            
            if function_name == "get_news":
                print(f"[{function_args.get('encText')}] 관련 뉴스를 검색 중입니다...")
                function_response = get_news(encText=function_args.get("encText"))
                
                messages.append({
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": json.dumps(function_response, ensure_ascii=False),
                })

        second_response = openAi_client.chat.completions.create(
            model=model,
            messages=messages,
            temperature = 0,
        )
        return second_response.choices[0].message.content
    
    return response_message.content

'''
input_list = [
+) 시스템 프롬프트/developer prompt
1. user가 질문한 내용 [role:user]
2. user질문에 대해 ai가 함수를 실행시키라고 하는 명령 [function_call]
3. 명령에 대한 실행, 즉 함수의 결과 [function_call_out]
+) user의 명령: 요약해줘 와 같은 것들을 넣을 수 있음 input_list + input  ai에게 역할을 부여하면 좋음(system prompt)
Instruction, developer user assistant

원래 system -> developer

]
'''

# main
if __name__ == "__main__":
    print("질문을 입력하세요 (예: 요즘 IT 관련 뉴스가 뭐야?):")
    question = sys.stdin.readline().strip()
    if question:
        print("\n--- 결과 ---")
        print(run_conversation(question))

# def run_conversation(user_prompt):

#     input_list = [{"role":"user","content":user_prompt}]

#     response = openAi_client.responses.create(
#         model=model,
#         input=input_list,
#         tools=tools,
#     )

#     input_list += response.output


#     for item in response.output:
#         if item.type == "function_call":
#             if item.name == "get_news":
#                 recent_news = get_news(**json.loads(item.arguments))

#                 input_list.append({
#                     "type": "function_call_output",
#                     "call_id": item.call_id,
#                     "output": json.dumps({
#                         "recent_news": recent_news
#                     })
#                 })
    
#     response = openAi_client.responses.create(
#         model=model,
#         instructions="Respond only with news generated by a tool. 뉴스의 제목은 그대로 사용한다 제목은 따로 두고 내용을 요약해서 보여줌",
#         tools=tools,
#         input=input_list,
#     )

#     return response.output_text



# print("대화를 시작합니다.")
# question = input()
# print("Final output:")

# print(run_conversation(question))

